[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "autodoip"
version = "0.1.2"
description = "DoIP (Diagnostics over IP) transport layer for automotive UDS — ISO 13400"
readme = "README.md"
requires-python = ">=3.14"
license = {text = "MIT"}
authors = [
    {name = "leno augenstern"},
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: System :: Networking",
]
dependencies = []

[project.urls]
Homepage = "https://github.com/leno166/autodoip"
Source = "https://github.com/leno166/autodoip"

[dependency-groups]
dev = [
    "build>=1.5.0",
    "pytest>=9.0.3",
    "twine>=6.2.0",
]